[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/caelix-dev/embark"
homepage = "https://github.com/caelix-dev/embark"
readme = "README.md"
rust-version = "1.87"

[workspace.dependencies]
embark-format = { version = "0.1.0", path = "crates/embark-format", default-features = false }
embark-codec = { version = "0.1.0", path = "crates/embark-codec", default-features = false }
embark-crypt = { version = "0.1.0", path = "crates/embark-crypt", default-features = false }
embark-macros = { version = "0.1.0", path = "crates/embark-macros" }
